name: CI Tests (uv + Container)

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-latest

    container:
      image: python:3.13.7-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: "3.13.7"

    - name: Install dependencies
      run: uv sync --frozen --no-group device

    - name: Run unittests
      run: uv run python -m unittest discover .
